shell: main.c variables.c variables.h command_parser.c command_parser.h commands.c commands.h environment.c environment.h file_processing.c file_processing.h
	gcc -o shell main.c variables.c  command_parser.c commands.c environment.c file_processing.c -I.
